language: ruby
rvm:
- ruby-2.2.3

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - build-essential
    - zlib1g-dev

env:
  global:
  - secure: "0FUWv3G8fBTOhQ72en3jv6sNuejGukz//SdyTHvPLX27gw+7Qa3Qp0aIC8VGnjZYDdCX9KcULFb9LNu79RD67WZ2pqY478OQRB7AqcL+ivjilBYiiPGGYqPvTmkXox70F0X8pGmOt0jJScWWFeN+9u96a15QVC8rTDhXaLdfeAjASyKUev+lkRp7YuLkm0S0m2wbuy81hB8g4vbSq2RJF30HRANvmP4bWPZMxSCUGzO0afbFk2zvKafbUezkaa1xNxN26A1V2emeXyf5+Hf3h/nI6R2o69Ae0mN9i828+S3TquboYbpqeotKFH3m3fZ8JfXx3y632hbVo3w7kwW7jBZ8I/uSOv8IUHhWiQD5AeAnRM8eYbvMkwEI13cpQAed8FTDdAoCFqkw83DSDEFnalZLq3kD97cgTXtvS7fB3nfLol96XiGoJQeAZJRjjwIE8AZ5YrVOj8s8SHVV6jyBCUycbzKXr2NGvgWmLTtOwg1w96eWusNKEBp4IyFIm0y1bjIq7LskGvpRcHYzTyKn3mJq4owGOtm4kHU8AtaeKb2VA51Dt4HqEOzurORnByTsu51ysJxMLI//51V5RwuxJQPPxWD00FnXImpTiHSfrw3YXmx2GnxxdF1v+V7ABwxqZA83ilsoZ+vH1eeJoXKz+eq+Zhm2qPTWaxIZ+jkYIUE="

install:
- gem install jekyll github-pages

script:
- make build
- make deploy
