
title: Jakob Jarosch
description: GitHub user page of Jakob Jarosch (@foxylion)
baseurl: ""
url: "https://jakob.soy"
repository: "https://github.com/foxylion/foxylion.github.io"
google_analytics: UA-2072722-5

permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : rouge

excerpt_separator: <!--more-->

source: .
destination: _site
sass:
  sass_dir: _scss
  style: compressed

social:
- slug: github
  link: https://github.com/foxylion
- slug: stackoverflow
  link: https://stackoverflow.com/users/439126/foxylion
- slug: linkedin
  link: https://linkedin.com/in/jakobjarosch
- slug: xing
  link: https://www.xing.com/profile/Jakob_Jarosch
- slug: facebook
  link: https://facebook.com/jakobjarosch
- slug: googleplus
  link: https://plus.google.com/u/0/+JakobJarosch
- slug: twitter
  link: https://twitter.com/foxylion
- slug: reddit
  link: https://www.reddit.com/user/foxylion
- slug: spotify
  link: https://play.spotify.com/user/foxylion
- slug: lastfm
  link: https://www.last.fm/de/user/foxylion
- slug: youtube
  link: https://www.youtube.com/user/foxylion
- slug: instagram
  link: https://www.instagram.com/foxylion
- slug: 500px
  link: https://500px.com/foxylion
- slug: flickr
  link: https://www.flickr.com/photos/foxylion
- slug: steam
  link: https://steamcommunity.com/id/foxylion
- slug: mail
  link: mailto:dev@jakobjarosch.de
- slug: skype
  link: skype://foxylion?add
